language: ruby

cache: bundler

rvm:
  - 2.2.1

services:
  - redis-server

# start X frame buffer for Selenium tests
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

notifications:
  email:
    on_failure: change
